name: build

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: cargo test --no-run
    - name: Test
      run: cargo test